# Generated by Django 3.0.7 on 2020-07-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.CharField(choices=[('technical', 'Technical'), ('value', 'Value'), ('growth', 'Growth')], default='green', max_length=9),
        ),
    ]
