# Generated by Django 3.0.7 on 2020-07-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200707_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='color',
            new_name='type',
        ),
    ]
